version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.18.5
    - 3.18.6
    - 3.18.8
    - 3.19.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: uswds-jekyll
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: kramdown
    versions:
    - 2.3.0
